version: "3.8"

services:
  kanboard:
    image: kanboard/kanboard:latest
    container_name: kanboard
    ports:
      - "8080:80"
    volumes:
      - ./data:/var/www/app/data
      - ./plugins:/var/www/app/plugins
    restart: unless-stopped
